version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "OpenTelemetry.*"

  - package-ecosystem: "npm"
    directory: "/Dotify.UI"
    schedule:
      interval: "weekly"
